### ISSUE TITLE
Which pre-trained ResNet-200 model did you use?

### ISSUE THREAD

**Issue by jhliu17** [LuoweiZhou/densecap#2]
Dear author @LuoweiZhou , thanks for your help in my last issue. Now, I meet another problem 😂 Could you release the pre-trained ResNet-200 model which you used to extract appearance feature?

**Comment by LuoweiZhou** [comment]
Sure, please refer to [here](https://github.com/salesforce/densecap/issues/3) and [here](https://github.com/salesforce/densecap/issues/5)

**Comment by jhliu17** [comment]
Thanks for answering!
