### ISSUE TITLE
not getting train_samplelist.pkl file

### ISSUE THREAD

**Issue by DeepaliVerma** [LuoweiZhou/densecap#5]
Sir, can you please tell me where i get this pickle file

**Comment by LuoweiZhou** [comment]
@DeepaliVerma It will be generated the first time you run the code, as in [here](https://github.com/LuoweiZhou/densecap/blob/master/data/anet_dataset.py#L186).

**Comment by DeepaliVerma** [comment]
Thank u so much sir, but now I m facing another issue related to
"AttributeError: 'ActionPropDenseCap' object has no attribute 'module'"
please suggest me way to the solution and also I m using a single GPU.
