### ISSUE TITLE
Datasets and pretrained models are taken down

### ISSUE THREAD

**Issue by jeevana28** [LuoweiZhou/densecap#8]
Datasets and pretrained models sites are taken down, even after trying in multiple browsers i am not able to open these sites

**Comment by LuoweiZhou** [comment]
@jeevana28 Thanks for your feedback. It turned out our web server is down. This will be fixed asap (likely by the coming Monday).

**Comment by LuoweiZhou** [comment]
It should be back on now. Please let me know if the problem persists.
